import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/beranda.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Perumahan Online</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.header}></div>
        <div className={styles.list}></div>
        <div className={styles.logo}></div>
      </main>
      <main className={styles.cover_halaman}>
        <div className={styles.deskripsi}>
            <p1>Website Perumahan Online</p1>
            <p2>Cari rumah yang diidamkan dengan cepat dan mudah</p2>
        </div>
        <div className={styles.kotak1}>
        <Link href="/daftar" passHref><p1 className={styles.kotak1_daftar}>Daftar Sekarang</p1></Link>
        </div>
      </main>
      <main className={styles.footer}>
        <div className={styles.footer_posisi}>
            <div className={styles.footer_tulisan1}>
                <p1>Tentang</p1>
                <p2>Kontak</p2>
            </div>
            <div className={styles.footer_sosmed1}>
                <p3></p3>
                <p4></p4>
                <p5></p5>
            </div>
            <div className={styles.footer_copyright}>
                <p6>© Copyright 2022 - Kelompok Marka</p6>
            </div>
        </div>
      </main>
    </>
  )
}
