import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/beranda.module.css'
import Link from 'next/link'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter()

  return (
    <>
      <Head>
        <title>Perumahan Online</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.header}>
        <div className={styles.logo}></div>
        <Link href="/beranda(user)" passHref><h1 className={styles.tombol_beranda}>Beranda</h1></Link>
        <Link href="/koleksi" passHref><h1 className={styles.tombol_koleksi}>Koleksi</h1></Link>
        <Link href="/survey(user)" passHref><h1 className={styles.tombol_survey}>Survey</h1></Link>
        <Link href="/dashboard(user)" passHref><h1 className={router.pathname==="/dashboard(user)" ? styles.tombol_dashboard_active : styles.tombol_dashboard}>Dashboard</h1></Link>
        <div class="dropdown">
            <button className={styles.profile} type="button" data-bs-toggle="dropdown" aria-expanded="false"></button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="/beranda">Logout</a></li>
                </ul>
        </div>
        </div>
      </main>
      <main className={styles.tabel}>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th scope="col">NO</th>
              <th scope="col">Tipe Rumah</th>
              <th scope="col">Jenis Rumah</th>
              <th scope="col">Tanggal Pertemuan</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th scope="row">1</th>
              <td>TIPE A</td>
              <td>Desain Minimalis Ukuran 6x7 m</td>
              <td>07/Desember/2022</td>
            </tr>
            <tr>
              <th scope="row">2</th>
              <td>TIPE B</td>
              <td>Desain Minimalis Ukuran 7x5 m</td>
              <td>22/Desember/2022</td>
            </tr>
            <tr>
              <th scope="row">3</th>
              <td>TIPE C</td>
              <td>Desain Minimalis Ukuran 9x7 m</td>
              <td>01/Januari/2023</td>
            </tr>
            <tr>
              <th scope="row">4</th>
              <td></td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <th scope="row">5</th>
              <td></td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <th scope="row">6</th>
              <td></td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <th scope="row">7</th>
              <td></td>
              <td></td>
              <td></td>
            </tr>
          </tbody>
        </table>
      </main>
      <main className={styles.footer}>
        <div className={styles.footer_posisi}>
            <div className={styles.footer_tulisan1}>
                <p1>Tentang</p1>
                <p2>Kontak</p2>
            </div>
            <div className={styles.footer_sosmed1}>
                <p3></p3>
                <p4></p4>
                <p5></p5>
            </div>
            <div className={styles.footer_copyright}>
                <p6>© Copyright 2022 - Kelompok Marka</p6>
            </div>
        </div>
      </main>
    </>
  )
}
