import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/admin.module.css'
import Link from 'next/link'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    const router = useRouter()
  return (
    <>
      <Head>
        <title>Perumahan Online</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.header}></div>
        <div className={styles.logo}></div>
        <Link href="/koleksi(admin)" passHref><h1 className={router.pathname==="/koleksi(admin)" ? styles.tombol_koleksi_active : styles.tombol_koleksi}>Koleksi</h1></Link>
        <Link href="/data(admin)" passHref><h1 className={styles.tombol_data}>Data</h1></Link>
        <Link href="/laporan(admin)" passHref><h1 className={styles.tombol_laporan}>Laporan</h1></Link>
        <div class="dropdown">
            <button className={styles.profile} type="button" data-bs-toggle="dropdown" aria-expanded="false"></button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="/beranda">Logout</a></li>
                </ul>
        </div>
      </main>
      <main className={styles.kotak_koleksi}>
        <div className={styles.update_koleksi}>Update Koleksi</div>
        <div className={styles.garis_koleksi}></div>
        <div className={styles.tulisan1}>Tipe Rumah</div>
        <div className={styles.box_form1}>
          <div class="input-group mb-3">
              <input type="text" class="form-control" placeholder="" aria-label="" aria-describedby="button-addon2"></input>
          </div>
        </div>
        <div className={styles.tulisan2}>Jenis Rumah</div>
        <div className={styles.box_form2}>
          <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="" aria-label="" aria-describedby="button-addon2"></input>
          </div>
        </div>
        <div className={styles.tulisan3}>Catatan</div>
        <div className={styles.box_form3}>
          <div class="input-group mb-3">
              <textarea type="text" class="form-control" placeholder="" aria-label="" aria-describedby="button-addon2"></textarea>
          </div>
        </div>
        <div className={styles.tulisan4}>File</div>
        <div className={styles.box_form4}>
        <div class="input-group">
          <input type="file" class="form-control" id="inputGroupFile04" aria-describedby="inputGroupFileAddon04" aria-label="Upload"></input>
        </div>
        </div>
        <div className={styles.tulisan5}>Tagihan</div>
        <div className={styles.box_form5}>
          <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="" aria-label="" aria-describedby="button-addon2"></input>
          </div>
        </div>
        <div className={styles.garis_koleksi2}></div>
        <div className={styles.tombol_batal}>
          <div className={styles.logo_tombol_batal}></div>
          <div className={styles.tulisan_tombol_batal}>Batal</div>
        </div>
        <div className={styles.tombol_simpan}>
          <div className={styles.logo_tombol_simpan}></div>
          <div className={styles.tulisan_tombol_simpan}>Simpan</div>
        </div>
      </main>
      <main className={styles.footer}>
        <div className={styles.footer_posisi}>
            <div className={styles.footer_tulisan1}>
                <p1>Tentang</p1>
                <p2>Kontak</p2>
            </div>
            <div className={styles.footer_sosmed1}>
                <p3></p3>
                <p4></p4>
                <p5></p5>
            </div>
            <div className={styles.footer_copyright}>
                <p6>© Copyright 2022 - Kelompok Marka</p6>
            </div>
        </div>
      </main>
    </>
  )
}
