import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Link from 'next/link'
import styles from '../styles/koleksi.module.css'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.header}>
            <div className={styles.peron}></div>
            <Link href="/beranda(user)" passHref><p className={styles.tombol_beranda}>Beranda</p></Link>
            <Link href="/koleksi" passHref><h1 className={router.pathname==="/koleksi" ? styles.tombol_koleksi_active : styles.tombol_koleksi}>Koleksi</h1></Link>
            <Link href="/survey(user)" passHref><p className={styles.tombol_survey}>Survey</p></Link>
            <Link href="/dashboard(user)" passHref><p className={styles.tombol_dashboard}>Dashboard</p></Link>
            <div className={styles.login}></div>
        </div>
        <div className={styles.box1}>
            <div className={styles.tipea}></div>
            <div className={styles.font1box1}>
                <p1>TIPE A Desain Minimalis Ukuran 6x7 m</p1>
                <p2>Garasi, Taman, 2 kamar, 1 kamar mandi Progress rumah 70 %</p2>
                <p3>Harga Rp. 70.000.000 Cicilan 5x</p3>
            </div>
        </div>
        <div className={styles.boxray1}></div>
        <div className={styles.box2}>
            <div className={styles.tipeb}></div>
            <div className={styles.font1box2}>
                <p1>TIPE B Desain Minimalis Ukuran 7x5 m</p1>
                <p2>Garasi, Taman, 2 kamar, 1 kamar mandi, ruang keluarga. Progress rumah 30 %</p2>
                <p3>Harga Rp. 76.000.000 Cicilan 3x</p3>
            </div>
        </div>
        <div className={styles.boxray2}></div>
        <div className={styles.box3}>
            <div className={styles.tipec}></div>
            <div className={styles.font1box2}>
                <p1>TIPE C Desain Minimalis Ukuran 9x7 m</p1>
                <p2>Garasi, Taman, 3 Kamar, ruang tamu, 2 kamar mandi. Progress rumah 30 %</p2>
                <p3>Harga Rp. 92.000.000 Cicilan 5x</p3>
            </div>
        </div>
        <div className={styles.boxray3}></div>
        <div className={styles.footer}>
            <div className={styles.boxfoot}>
                <div className={styles.tk}></div>
                <div className={styles.sosmed}></div>
                <p>© Copyright 2022 - Kelompok Marka</p>
            </div>
        </div>
      </main>
    </>
  )
}
