import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/login.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Perumahan Online</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <div className={styles.logo2}></div>
      <div className={styles.form1}>
        <div class="input-group mb-3">
          <input type="text" class="form-control" placeholder="ID Pengguna" aria-label="ID Pengguna" aria-describedby="button-addon2"></input>
        </div>
      </div>
      <div className={styles.kotak3_daftar}>
      <Link href="/beranda" passHref><p1 className={styles.kotak1_daftar}>Reset</p1></Link>
      </div>
        <div className={styles.header}>
            <div className={styles.kotak2_daftar}>
                <p>Daftar</p>
            </div>
            <div className={styles.kotak2_masuk}>
                <p>Masuk</p>
            </div>
        </div>
        <div className={styles.list}></div>
        <div className={styles.logo}></div>
      </main>
      <main className={styles.footer}>
        <div className={styles.footer_posisi}>
            <div className={styles.footer_tulisan1}>
                <p1>Tentang</p1>
                <p2>Kontak</p2>
            </div>
            <div className={styles.footer_sosmed1}>
                <p3></p3>
                <p4></p4>
                <p5></p5>
            </div>
            <div className={styles.footer_copyright}>
                <p6>© Copyright 2022 - Kelompok Marka</p6>
            </div>
        </div>
      </main>
    </>
  )
}
