import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/beranda.module.css'
import Link from 'next/link'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter()

  return (
    <>
      <Head>
        <title>Perumahan Online</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.header}>
        <div className={styles.logo}></div>
        <Link href="/beranda(user)" passHref><h1 className={styles.tombol_beranda}>Beranda</h1></Link>
        <Link href="/koleksi" passHref><h1 className={styles.tombol_koleksi}>Koleksi</h1></Link>
        <Link href="/survey(user)" passHref><h1 className={router.pathname==="/survey(user)" ? styles.tombol_survey_active : styles.tombol_survey}>Survey</h1></Link>
        <Link href="/dashboard(user)" passHref><h1 className={styles.tombol_dashboard}>Dashboard</h1></Link>
        <div class="dropdown">
            <button className={styles.profile} type="button" data-bs-toggle="dropdown" aria-expanded="false"></button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="/beranda">Logout</a></li>
                </ul>
        </div>
        </div>
      </main>
      <main className={styles.isi}>
        <div className={styles.tulisan_intro}>Silahkan mengisi data dibawah untuk melakukan pertemuan kedua pihak</div>
        <div className={styles.garis1}></div>
        <div className={styles.form1}>
            <div class="input-group">
                <select class="form-select" id="inputGroupSelect04" aria-label="Example select with button addon">
                    <option selected>Tipe Rumah</option>
                    <option value="1">TIPE A</option>
                    <option value="2">TIPE B</option>
                    <option value="3">TIPE C</option>
                </select>
            </div>

        </div>
        <div className={styles.form2}>
            <div class="input-group mb-3">
                <input type="text" class="form-control" placeholder="Jenis Rumah" aria-label="Jenis Rumah" aria-describedby="button-addon2"></input>
            </div>
        </div>
        <div className={styles.form3}>
            <div class="input-group mb-3">
                <input type="text" class="form-control" placeholder="Tanggal/Bulan/Tahun Pertemuan" aria-label="Tanggal/Bulan/Tahun Pertemuan" aria-describedby="button-addon2"></input>
            </div>
        </div>
        <div className={styles.form4}>
            <div class="input-group mb-3">
                <textarea type="text" class="form-control" placeholder="Catatan" aria-label="Catatan" aria-describedby="button-addon2"></textarea>
            </div>
        </div>
        <div className={styles.tombol_simpan}>
            <Link href="/beranda(user)" passHref><p1 className={styles.tombol_simpan1}>Simpan</p1></Link>
        </div>
      </main>
      <main className={styles.footer}>
        <div className={styles.footer_posisi}>
            <div className={styles.footer_tulisan1}>
                <p1>Tentang</p1>
                <p2>Kontak</p2>
            </div>
            <div className={styles.footer_sosmed1}>
                <p3></p3>
                <p4></p4>
                <p5></p5>
            </div>
            <div className={styles.footer_copyright}>
                <p6>© Copyright 2022 - Kelompok Marka</p6>
            </div>
        </div>
      </main>
    </>
  )
}
